#! /bin/sh

xinput --set-prop 10 'libinput Accel Speed' -0.7 &
xinput --set-prop 20 'libinput Accel Speed' -0.7
setxkbmap -option grp:alt_shift_toggle us,ru &
pgrep -x sxhkd > /dev/null || sxhkd &


#single monitor 
#bspc monitor -d 1 2 3 4 5


#two monitors
bspc monitor HDMI-A-0 1 4
bspc monitor -d 2 3
xrandr --output HDMI-A-0 --above eDP


#theme
theme="greytheme"
themes_dir="/.config/bspwm/themes"

#hi
bspc config pointer_action1 move 
bspc config pointer_action2 resize_side 
bspc config pointer_action2 resize_corner

bspc config wm_name LG3D
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc config border_width        "2"
bspc config window_gap          "6"
bspc config normal_border_color "#2b3038"
bspc config active_border_color "#286c7899"
bspc config focused_border_color "#4944949"
bspc config presel_feedback_color "#286c78"



